alter table FE_WORK_RECORD add constraint FK_FE_WORK_RECORD_WORK_ORDER foreign key (WORK_ORDER_ID) references FE_WORK_ORDER(ID);
alter table FE_WORK_RECORD add constraint FK_FE_WORK_RECORD_EMPLOYEE foreign key (EMPLOYEE_ID) references FE_EMPLOYEE(ID);
create index IDX_FE_WORK_RECORD_WORK_ORDER on FE_WORK_RECORD (WORK_ORDER_ID);
create index IDX_FE_WORK_RECORD_EMPLOYEE on FE_WORK_RECORD (EMPLOYEE_ID);
