alter table FE_MACHINE_PROCESSES add constraint FK_FE_MACHINE_PROCESSES_MACHINE foreign key (MACHINE_ID) references FE_MACHINE(ID);
create index IDX_FE_MACHINE_PROCESSES_MACHINE on FE_MACHINE_PROCESSES (MACHINE_ID);
