alter table FE_EMPLOYEE add constraint FK_FE_EMPLOYEE_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references FE_DEPARTMENT(ID);
create unique index IDX_FE_EMPLOYEE_UNIQ_NO_ on FE_EMPLOYEE (NO_) ;
create index IDX_FE_EMPLOYEE_ON_DEPARTMENT on FE_EMPLOYEE (DEPARTMENT_ID);
