alter table FE_MACHINE_PROCESSES add constraint FK_FE_MACHINE_PROCESSES_ON_MACHINE foreign key (MACHINE_ID) references FE_MACHINE(ID);
create unique index IDX_FE_MACHINE_PROCESSES_UNQ on FE_MACHINE_PROCESSES (MACHINE_ID, PROCESS_TYPE) ;
create index IDX_FE_MACHINE_PROCESSES_ON_MACHINE on FE_MACHINE_PROCESSES (MACHINE_ID);
