alter table FE_WORK_ORDER add constraint FK_FE_WORK_ORDER_ON_INVENTORY_ITEM foreign key (INVENTORY_ITEM_ID) references FE_INVENTORY_ITEM(ID);
alter table FE_WORK_ORDER add constraint FK_FE_WORK_ORDER_ON_DEFAULT_MACHINE foreign key (DEFAULT_MACHINE_ID) references FE_MACHINE(ID);
alter table FE_WORK_ORDER add constraint FK_FE_WORK_ORDER_ON_BACKUP_MACHINES foreign key (BACKUP_MACHINES_ID) references FE_MACHINE(ID);
create unique index IDX_FE_WORK_ORDER_UNIQ_NO_ on FE_WORK_ORDER (NO_) ;
create index IDX_FE_WORK_ORDER_ON_INVENTORY_ITEM on FE_WORK_ORDER (INVENTORY_ITEM_ID);
create index IDX_FE_WORK_ORDER_ON_DEFAULT_MACHINE on FE_WORK_ORDER (DEFAULT_MACHINE_ID);
create index IDX_FE_WORK_ORDER_ON_BACKUP_MACHINES on FE_WORK_ORDER (BACKUP_MACHINES_ID);
